### ISSUE TITLE
Dead link for conll2003_spacy.tar.gz

### ISSUE THREAD

**Issue by wpnbos** [NorskRegnesentral/weak-supervision-for-NER#2]
Hi, 

I am trying to run your notebook, so I have to download all the data files and extract them into the data folder.
The links are in the readme of this repo, however, there's one link that appears to be dead, the one for `conll2003_spacy.tar.gz`. 

It'd be nice if someone could replace this link with a working one so that I can try out the code. 

Thanks!

**Comment by plison** [comment]
As I've guess you've noticed, we have moved the code to the `skweak` repository, where is where things will develop from now on.
